//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ro5setkom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ro5setkom.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock Exam.
        /// </summary>
        public static string Dashboard_MockExam {
            get {
                return ResourceManager.GetString("Dashboard_MockExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next milestone.
        /// </summary>
        public static string Dashboard_NextMilestone {
            get {
                return ResourceManager.GetString("Dashboard_NextMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Progress.
        /// </summary>
        public static string Dashboard_Progress {
            get {
                return ResourceManager.GetString("Dashboard_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake Mock Exam.
        /// </summary>
        public static string Dashboard_RetakeMockExam {
            get {
                return ResourceManager.GetString("Dashboard_RetakeMockExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mock Exam.
        /// </summary>
        public static string Dashboard_StartMockExam {
            get {
                return ResourceManager.GetString("Dashboard_StartMockExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dashboard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed ✓ — you can retake anytime..
        /// </summary>
        public static string MockExam_Completed {
            get {
                return ResourceManager.GetString("MockExam_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake.
        /// </summary>
        public static string MockExam_Retake {
            get {
                return ResourceManager.GetString("MockExam_Retake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Mock Exam.
        /// </summary>
        public static string MockExam_Start {
            get {
                return ResourceManager.GetString("MockExam_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock Exam.
        /// </summary>
        public static string MockExam_Title {
            get {
                return ResourceManager.GetString("MockExam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All theoretical modules complete! Take the mock exam to unlock theory booking..
        /// </summary>
        public static string MockExam_UnlockMessage {
            get {
                return ResourceManager.GetString("MockExam_UnlockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Complete.
        /// </summary>
        public static string Modules_Complete {
            get {
                return ResourceManager.GetString("Modules_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Modules_Continue {
            get {
                return ResourceManager.GetString("Modules_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Modules_Locked {
            get {
                return ResourceManager.GetString("Modules_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No practical modules available yet..
        /// </summary>
        public static string Modules_NonePractical {
            get {
                return ResourceManager.GetString("Modules_NonePractical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No theoretical modules available..
        /// </summary>
        public static string Modules_NoneTheoretical {
            get {
                return ResourceManager.GetString("Modules_NoneTheoretical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical Modules.
        /// </summary>
        public static string Modules_Practical {
            get {
                return ResourceManager.GetString("Modules_Practical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Modules_Review {
            get {
                return ResourceManager.GetString("Modules_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Module.
        /// </summary>
        public static string Modules_Start {
            get {
                return ResourceManager.GetString("Modules_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theoretical Modules.
        /// </summary>
        public static string Modules_Theoretical {
            get {
                return ResourceManager.GetString("Modules_Theoretical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Modules.
        /// </summary>
        public static string Modules_Title {
            get {
                return ResourceManager.GetString("Modules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Quiz_Correct {
            get {
                return ResourceManager.GetString("Quiz_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Passed Yet.
        /// </summary>
        public static string Quiz_Failed {
            get {
                return ResourceManager.GetString("Quiz_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Quiz_Incorrect {
            get {
                return ResourceManager.GetString("Quiz_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed!.
        /// </summary>
        public static string Quiz_Passed {
            get {
                return ResourceManager.GetString("Quiz_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake Quiz.
        /// </summary>
        public static string Quiz_RetakeQuiz {
            get {
                return ResourceManager.GetString("Quiz_RetakeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Quiz_Score {
            get {
                return ResourceManager.GetString("Quiz_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Quiz.
        /// </summary>
        public static string Quiz_Submit {
            get {
                return ResourceManager.GetString("Quiz_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Quiz.
        /// </summary>
        public static string Quiz_TakeQuiz {
            get {
                return ResourceManager.GetString("Quiz_TakeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string Status_InProgress {
            get {
                return ResourceManager.GetString("Status_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string Status_NotStarted {
            get {
                return ResourceManager.GetString("Status_NotStarted", resourceCulture);
            }
        }
    }
}
